### PR TITLE
Update Sample Project with Test

### PR DESCRIPTION
**Pull request by alsoicode**
Hello, I'd like to share the minimum setup I needed to add to the requirements and configuration to be able to run an e2e test. The main project documentation also needs some updates in this regard.

This PR adds:
- jest, ts-jest and supertest and their respective type definitions to the dev dependencies.
- the minimum jest configuration in package.json to be able to transform and test TypeScript files as well as packages that aren't written in TypeScript, like Express.
- A minor change to tsconfig.json to allow synthetic default imports, which was necessary to be able to import and instantiate Express in a test.
- A minimal e2e test to run against the root route.

### CODE REVIEW

**Comment by alsoicode** [comment]
@kamilmysliwiec Would you mind taking a look at my pull request if you have some time?

**Comment by alsoicode** [comment]
@kamilmysliwiec I've fixed the merge conflicts.

**Comment by kamilmysliwiec** [comment]
Hi @alsoicode,
The PR is cool, but I'm worried whether we should force people to use a particular test runner such as Jest in this case. What if someone would prefer ava or any other library? It makes this project no longer a starter, but rather a really small boilerplate instead. 🙁

**Comment by alsoicode** [comment]
Well, it's just a sample and starting point to at least get something going. I primarily work with Angular on the front-end, but I have experience with Aurelia, React, Backbone, Knockout and lots of other frameworks/libraries.

Sometimes it's nice to not have to make too many decisions and simply be able to follow the direction established by the core team. I know with Angular that I'm going to use their testing facilities, and I know they're going to work.

Of course, there are other testing frameworks/libraries out there, but will they really make a tremendous impact on being able to write an effective test? and how much complexity would it add to Nest to be able to abstract those? Just things to think about.

**Comment by Renader** [comment]
@alsoicode I coudn't agree more. That is exactly what Angular is doing for us - providing an ecosystem and guide us on how to do it. So not every developer has to figure this out on his own. And i think nest.js should do the same. 

Plus, it is always easier to replace the test setup with your custom choice then to initially setup your testing setup. Especially with TypeScript. I love TypeScript and it helps, but it does make test setup even a little harder. I've myself struggled and wasted some hours to get testing to work properly with nestjs.

**Comment by alsoicode** [comment]
@kamilmysliwiec I've fixed the merge conflicts. I don't think adding a sample configuration is forcing people to use any particular test runner. It's just an example to get started. People will always add or change these types of things to suit their needs.

**Comment by alsoicode** [comment]
@Renader I think so as well. Nest fills a big gap if you want to be able to use TypeScript for the backend, and one of the keys to a high adoption rate is outstanding documentation and code examples.

Take Django for example; their documentation is some of the best around in my opinion, which makes learning it a lot easier. You can simply follow the docs and everything "just works". Nest needs the same if it wants to enjoy a high adoption rate, which I hope it does!

At my work, I'm steering our backends away from Java and toward a Node/TypeScript solution. We also use Angular for our UIs, and with Nest's module pattern, it makes transitioning from front to back-end essentially painless.

I sincerely hope that Nest will increase in popularity, but to do that, it needs have great documentation and samples that work perfectly so that people can build on them, not fight with configuration issues or missing dependencies, etc.

**Comment by marcelfalliere** [comment]
I second this PR ! Tests should be included in the bootstrap. Actually I should have take 10 seconds to look at open PR in this repo, because I just did the same PR as you @alsoicode

**Comment by SelaO** [comment]
Why not make a branch for this?

**Comment by kamilmysliwiec** [comment]
Thank you for convincing me!

**Pull request merged**
