### PR TITLE
Switch nodemon over to tsc-watch, enable incremental builds.

### PR DESCRIPTION
**Pull request by Sacro**
Now tsc 3.4.1 is out, we can use some of the new features. I've left the tsconfig files as-is aside from excluding the "dist" folder.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Is `tsc-watch` library mature enough to recommend its usage in the starter project? Results look promising and we should definitely take advantage of the new incremental builds in TS. I'm slightly afraid about `tsc-watch` though.

**Comment by Sacro** [comment]
Looking at the tsc-watch bugs, it seems it does have issues with non English locales, that's not great. I'll see what alternatives there are.

**Comment by kamilmysliwiec** [comment]
What about running `tsc --watch` and `nodemon` concurrently?

**Comment by Sacro** [comment]
That would work, but the nice thing about `tsc-watch` is it waits for the build to be succesful or to fail before moving on. Using [wait-on](https://www.npmjs.com/package/wait-on) alongside [concurrently](https://www.npmjs.com/package/concurrently) might be a nice solution

**Comment by kamilmysliwiec** [comment]
True. Anyways, `tsc` + `nodemon` sounds like a more stable integration + is much faster. Should we move with this one for now? :)

**Comment by Sacro** [comment]
Sounds good to me

**Comment by Sacro** [comment]
I'll close this and we can move to #124

**Pull request closed without merging**
