### PR TITLE
feat(*): better conform to Angular style guide

### PR DESCRIPTION
**Pull request by wbhob**
flatter folder structure and more modular. Has more features out of the box to help draw connections. The Angular CLI also has a component and service out of the box to help you get started, so I added it to this starter.

### CODE REVIEW

**Comment by wbhob** [comment]
@ThomRick ...this

**Comment by kamilmysliwiec** [comment]
Hi @wbhob,
Thanks! There's the same situation as here https://github.com/nestjs/typescript-starter/pull/12 🙁

**Comment by wbhob** [comment]
Yeah, I saw that.

**Comment by kamilmysliwiec** [comment]
Don't be angry 🙁 I'd love to see few better starter projects, which provides more features out-of-the-box. Maybe let's consider to create one!

**Comment by wbhob** [comment]
I'm not angry 😄 I understand your logic completely. I'd love to discuss a good roadmap for building an ecosystem of starters that makes sense for a wide range of developers, and when CLI v2 comes out, we'll bake those starters into the CLI functionality as well.

**Pull request closed without merging**
